debug: true
server:
  port: 3000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin123
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update # none, create, update ...
  sql:
    init:
      platform: postgresql
      mode: always
    output:
      ansi:
        enabled: always
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR


#jwt-secret-key: QmFja2Jhc2VCYWNrZW5kRGV2ZWxvcGVyQXNzaWdubWVudE1vdmllc0FQSVZpamFuaQ==
jwt-secret-key: ADbvPxM+rGG4QRnj60LHKEOLyxlwFNFN8XTb6a1k2M/IxSr9VKsQisC2DpDcrdiU
