debug: true
server:
  port: 3000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin123
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none # none, create ...
  sql:
    init:
      platform: postgresql
      mode: always
    output:
      ansi:
        enabled: always
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR